### ISSUE TITLE
mobile-fixed-columns-table部分资源加载失效

### ISSUE THREAD

**Issue by xuanfeng** [ufologist/mobile-fixed-columns-table#1]
GET http://datatables.net/release-datatables/extras/FixedColumns/media/js/FixedColumns.min.js 404 (Not Found) demo12.html:46
Uncaught ReferenceError: FixedColumns is not defined datatables.mobile-fixed-columns-table.js:192

列不能固定

**Comment by ufologist** [comment]
已经修改为通过 rawgithub 来引用本项目中的文件, 感谢你提出的问题
