### ISSUE TITLE
Uncaught TypeError: Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by weituotian** [ufologist/mobile-fixed-columns-table#2]
Uncaught TypeError: Cannot read property 'msie' of undefined
    at Object._getScrollbarWidth (jquery.scrollFixedTable.js:1137)
    at HTMLTableElement.setup (jquery.scrollFixedTable.js:712)
    at HTMLTableElement.<anonymous> (jquery.scrollFixedTable.js:687)
    at Function.each (jquery-2.2.3.min.js:2)
    at n.fn.init.each (jquery-2.2.3.min.js:2)
    at n.fn.init.init (jquery.scrollFixedTable.js:681)
    at n.fn.init.$.fn.scrollFixedTable (jquery.scrollFixedTable.js:1159)
    at HTMLDocument.<anonymous> (index.html?_ijt=plirannukacjll8g6avq8a4oce:154)
    at i (jquery-2.2.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.3.min.js:2)

```
            _getScrollbarWidth: function() {
            	var scrollbarWidth = 0;
            	
            	if ( !scrollbarWidth ) {
					if ( $.browser.msie ) {
						var $textarea1 = $('<textarea cols="10" rows="2"></textarea>')
								.css({ position: 'absolute', top: -1000, left: -1000 }).appendTo('body'),
							$textarea2 = $('<textarea cols="10" rows="2" style="overflow: hidden;"></textarea>')
								.css({ position: 'absolute', top: -1000, left: -1000 }).appendTo('body');
						scrollbarWidth = $textarea1.width() - $textarea2.width() + 2; // + 2 for border offset
						$textarea1.add($textarea2).remove();
					} else {
						var $div = $('<div />')
							.css({ width: 100, height: 100, overflow: 'auto', position: 'absolute', top: -1000, left: -1000 })
							.prependTo('body').append('<div />').find('div')
								.css({ width: '100%', height: 200 });
						scrollbarWidth = 100 - $div.width();
						$div.parent().remove();
					}
				}
				
				return scrollbarWidth;
            }
```

**Comment by ufologist** [comment]
plase use jQuery 1.8.2

**Comment by weituotian** [comment]
jQuery 1.8.2 does solve this problem, even 1.12 can not solve

what is the problem in high jquery version

**Comment by ufologist** [comment]
[jQuery.browser](http://api.jquery.com/jQuery.browser/)

> version deprecated: 1.3, removed: 1.9
>
> Contains flags for the useragent, read from navigator.userAgent. This property was removed in jQuery 1.9 and is available only through the `jQuery.migrate` plugin.
>
> `$.browser.msie;`
